name = "jesse-chapter-factory"
main = "src/index.js"
compatibility_date = "2024-09-25"

[[d1_databases]]
binding = "DB"
database_name = "jesse-chapter-factory"
database_id = "dd91a213-b881-4b01-88bb-0e90dc43c825"
